import { ALL_VOCAB } from '@/data/curriculum'
import { bareNoun } from './utils'

/**
 * Hover-translation dictionary.
 *
 * Rule: it is better to show NOTHING than something wrong. Only surface forms
 * listed here (or derived from the course vocabulary) get a tooltip; anything
 * unknown is rendered as plain text.
 */

export interface Gloss {
  en: string
  /** grammatical note shown under the meaning, e.g. "der · plural: die Tische" */
  note?: string
}

/** Hand-checked forms: function words, pronouns and every inflection used in the course. */
const EXTRA: Record<string, Gloss> = {
  // ── pronouns ──
  ich: { en: 'I', note: 'pronoun' },
  du: { en: 'you', note: 'pronoun · informal singular' },
  er: { en: 'he', note: 'pronoun' },
  sie: { en: 'she / they', note: 'pronoun' },
  es: { en: 'it', note: 'pronoun' },
  wir: { en: 'we', note: 'pronoun' },
  ihr: { en: 'you (plural) / her / their', note: 'pronoun or possessive' },
  mich: { en: 'me', note: 'accusative of ich' },
  dir: { en: '(to) you', note: 'dative of du' },
  ihm: { en: '(to) him', note: 'dative of er' },
  ihnen: { en: '(to) you / them', note: 'dative · formal Ihnen' },
  uns: { en: 'us', note: 'accusative/dative of wir' },
  man: { en: 'one, people (in general)', note: 'impersonal pronoun' },
  das: { en: 'the / that, this', note: 'neuter article or demonstrative' },
  dieser: { en: 'this', note: 'demonstrative · masculine' },
  diese: { en: 'this, these', note: 'demonstrative · feminine/plural' },
  dieses: { en: 'this', note: 'demonstrative · neuter' },

  // ── articles & determiners ──
  der: { en: 'the', note: 'masculine article' },
  die: { en: 'the', note: 'feminine / plural article' },
  den: { en: 'the', note: 'masculine accusative' },
  dem: { en: 'the', note: 'masculine/neuter dative' },
  ein: { en: 'a, an', note: 'masculine/neuter' },
  eine: { en: 'a, an', note: 'feminine' },
  einen: { en: 'a, an', note: 'masculine accusative' },
  einem: { en: 'a, an', note: 'masculine/neuter dative' },
  einer: { en: 'a, an', note: 'feminine dative' },
  kein: { en: 'no, not a', note: 'masculine/neuter' },
  keine: { en: 'no, not a', note: 'feminine / plural' },
  keinen: { en: 'no, not a', note: 'masculine accusative' },
  mein: { en: 'my', note: 'masculine/neuter' },
  meine: { en: 'my', note: 'feminine / plural' },
  meinen: { en: 'my', note: 'masculine accusative' },
  dein: { en: 'your', note: 'informal · masculine/neuter' },
  deine: { en: 'your', note: 'informal · feminine/plural' },
  seine: { en: 'his, its', note: 'possessive · feminine/plural' },
  ihre: { en: 'her, their, your', note: 'possessive · feminine/plural' },
  unser: { en: 'our', note: 'possessive' },
  unsere: { en: 'our', note: 'possessive · feminine/plural' },
  euer: { en: 'your (plural)', note: 'possessive' },
  eure: { en: 'your (plural)', note: 'possessive · feminine/plural' },
  welche: { en: 'which', note: 'question word' },
  welches: { en: 'which', note: 'question word · neuter' },

  // ── sein / haben ──
  sein: { en: 'to be / his', note: 'verb or possessive' },
  bin: { en: 'am', note: 'sein · ich' },
  bist: { en: 'are', note: 'sein · du' },
  ist: { en: 'is', note: 'sein · er/sie/es' },
  sind: { en: 'are', note: 'sein · wir/sie/Sie' },
  seid: { en: 'are', note: 'sein · ihr' },
  haben: { en: 'to have', note: 'verb' },
  habe: { en: 'have', note: 'haben · ich' },
  hast: { en: 'have', note: 'haben · du' },
  hat: { en: 'has', note: 'haben · er/sie/es' },
  habt: { en: 'have', note: 'haben · ihr' },

  // ── verbs used across days 1–7 ──
  heißen: { en: 'to be called', note: 'verb' },
  heiße: { en: 'am called', note: 'heißen · ich' },
  heißt: { en: 'is called / are called', note: 'heißen · du, er/sie/es' },
  kommen: { en: 'to come', note: 'verb' },
  komme: { en: 'come', note: 'kommen · ich' },
  kommst: { en: 'come', note: 'kommen · du' },
  kommt: { en: 'comes', note: 'kommen · er/sie/es, ihr' },
  wohnen: { en: 'to live, to reside', note: 'verb' },
  wohne: { en: 'live', note: 'wohnen · ich' },
  wohnst: { en: 'live', note: 'wohnen · du' },
  wohnt: { en: 'lives', note: 'wohnen · er/sie/es' },
  lernen: { en: 'to learn', note: 'verb' },
  lerne: { en: 'learn', note: 'lernen · ich' },
  lernst: { en: 'learn', note: 'lernen · du' },
  lernt: { en: 'learns', note: 'lernen · er/sie/es' },
  sprechen: { en: 'to speak', note: 'verb' },
  spreche: { en: 'speak', note: 'sprechen · ich' },
  sprichst: { en: 'speak', note: 'sprechen · du · stem change i' },
  spricht: { en: 'speaks', note: 'sprechen · er/sie/es' },
  machen: { en: 'to do, to make', note: 'verb' },
  mache: { en: 'do, make', note: 'machen · ich' },
  machst: { en: 'do, make', note: 'machen · du' },
  macht: { en: 'does, makes', note: 'machen · er/sie/es' },
  arbeiten: { en: 'to work', note: 'verb' },
  arbeite: { en: 'work', note: 'arbeiten · ich' },
  arbeitest: { en: 'work', note: 'arbeiten · du · extra -e-' },
  arbeitet: { en: 'works', note: 'arbeiten · er/sie/es' },
  kaufen: { en: 'to buy', note: 'verb' },
  kaufe: { en: 'buy', note: 'kaufen · ich' },
  kauft: { en: 'buys', note: 'kaufen · er/sie/es' },
  suchen: { en: 'to look for', note: 'verb' },
  suche: { en: 'look for', note: 'suchen · ich' },
  sucht: { en: 'looks for', note: 'suchen · er/sie/es' },
  brauchen: { en: 'to need', note: 'verb' },
  brauche: { en: 'need', note: 'brauchen · ich' },
  braucht: { en: 'needs', note: 'brauchen · er/sie/es' },
  nehmen: { en: 'to take', note: 'verb' },
  nehme: { en: 'take', note: 'nehmen · ich' },
  nimmst: { en: 'take', note: 'nehmen · du · stem change' },
  nimmt: { en: 'takes', note: 'nehmen · er/sie/es' },
  verstehen: { en: 'to understand', note: 'verb' },
  verstehe: { en: 'understand', note: 'verstehen · ich' },
  verstehst: { en: 'understand', note: 'verstehen · du' },
  versteht: { en: 'understands', note: 'verstehen · er/sie/es' },
  wissen: { en: 'to know (a fact)', note: 'verb' },
  weiß: { en: 'know', note: 'wissen · ich/er/sie/es' },
  kennen: { en: 'to know (a person or place)', note: 'verb' },
  kenne: { en: 'know', note: 'kennen · ich' },
  kennt: { en: 'knows', note: 'kennen · er/sie/es' },
  lesen: { en: 'to read', note: 'verb' },
  lese: { en: 'read', note: 'lesen · ich' },
  liest: { en: 'reads', note: 'lesen · du, er/sie/es' },
  sehen: { en: 'to see', note: 'verb' },
  siehst: { en: 'see', note: 'sehen · du · stem change e → ie' },
  fahren: { en: 'to drive, to go', note: 'verb' },
  fährst: { en: 'drive, go', note: 'fahren · du · stem change a → ä' },
  fährt: { en: 'drives, goes', note: 'fahren · er/sie/es · stem change a → ä' },
  isst: { en: 'eat, eats', note: 'essen · du, er/sie/es · stem change e → i' },
  schlafen: { en: 'to sleep', note: 'verb' },
  schläfst: { en: 'sleep', note: 'schlafen · du · stem change a → ä' },
  schläft: { en: 'sleeps', note: 'schlafen · er/sie/es · stem change a → ä' },
  lest: { en: 'read', note: 'lesen · ihr' },
  sehe: { en: 'see', note: 'sehen · ich' },
  sieht: { en: 'sees', note: 'sehen · er/sie/es' },
  schreiben: { en: 'to write', note: 'verb' },
  schreibe: { en: 'write', note: 'schreiben · ich' },
  schreibt: { en: 'writes', note: 'schreiben · er/sie/es' },
  hören: { en: 'to hear, to listen', note: 'verb' },
  finden: { en: 'to find', note: 'verb' },
  finde: { en: 'find', note: 'finden · ich' },
  findet: { en: 'finds', note: 'finden · er/sie/es' },
  trinken: { en: 'to drink', note: 'verb' },
  trinke: { en: 'drink', note: 'trinken · ich' },
  essen: { en: 'to eat', note: 'verb' },
  gehen: { en: 'to go', note: 'verb' },
  gehe: { en: 'go', note: 'gehen · ich' },
  gehst: { en: 'go', note: 'gehen · du' },
  geht: { en: 'goes', note: 'gehen · er/sie/es' },
  studieren: { en: 'to study (at university)', note: 'verb' },
  studiere: { en: 'study', note: 'studieren · ich' },
  studiert: { en: 'studies', note: 'studieren · er/sie/es' },
  wiederholen: { en: 'to repeat, to revise', note: 'verb' },
  kostet: { en: 'costs', note: 'kosten · er/sie/es' },
  kosten: { en: 'to cost', note: 'verb' },
  helfen: { en: 'to help', note: 'verb' },
  erkläre: { en: 'explain', note: 'erklären · ich' },
  liegt: { en: 'lies, is located', note: 'liegen · er/sie/es' },
  schau: { en: 'look!', note: 'imperative of schauen' },
  spielt: { en: 'plays', note: 'spielen · er/sie/es' },
  kocht: { en: 'cooks', note: 'kochen · er/sie/es' },
  schlaf: { en: 'sleep!', note: 'imperative of schlafen' },
  können: { en: 'to be able to, can', note: 'modal verb' },
  kann: { en: 'can', note: 'können · ich/er/sie/es' },
  möchten: { en: 'would like', note: 'modal verb' },
  füllen: { en: 'to fill', note: 'verb · füllen … aus = fill in' },

  // ── question words ──
  wie: { en: 'how, what (in Wie heißt du?)', note: 'question word' },
  wo: { en: 'where (location)', note: 'question word' },
  woher: { en: 'where from (origin)', note: 'question word' },
  wohin: { en: 'where to (direction)', note: 'question word' },
  was: { en: 'what', note: 'question word' },
  wer: { en: 'who', note: 'question word' },
  wann: { en: 'when', note: 'question word' },
  warum: { en: 'why', note: 'question word' },

  // ── contractions and small words that appear constantly ──
  am: { en: 'on, at', note: 'an + dem · am Montag = on Monday' },
  im: { en: 'in the', note: 'in + dem' },
  ins: { en: 'to the, into the', note: 'in + das · ins Kino gehen' },
  zum: { en: 'to the', note: 'zu + dem' },
  zur: { en: 'to the', note: 'zu + der' },
  mir: { en: '(to) me', note: 'dative of ich · mir geht es gut' },
  dich: { en: 'you', note: 'accusative of du' },
  so: { en: 'so, like that', note: 'adverb · nicht so gern = not that much' },
  pro: { en: 'per', note: 'preposition · pro Woche = per week' },
  als: { en: 'as', note: 'ich arbeite als Reiseführer' },
  noch: { en: 'still, yet', note: 'adverb' },

  // ── further verb forms met in the lessons ──
  koche: { en: 'cook', note: 'kochen · ich' },
  kochst: { en: 'cook', note: 'kochen · du' },
  schwimme: { en: 'swim', note: 'schwimmen · ich' },
  schwimmst: { en: 'swim', note: 'schwimmen · du' },
  jogge: { en: 'jog', note: 'joggen · ich' },
  joggst: { en: 'jog', note: 'joggen · du' },
  joggt: { en: 'jogs', note: 'joggen · er/sie/es, ihr' },
  spiele: { en: 'play', note: 'spielen · ich' },
  spielen: { en: 'to play', note: 'verb' },
  treffen: { en: 'to meet', note: 'verb · wann treffen wir uns?' },
  steht: { en: 'stands, is placed', note: 'stehen · er/sie/es' },
  stehen: { en: 'to stand', note: 'verb' },
  reise: { en: 'travel', note: 'reisen · ich' },
  tanzen: { en: 'to dance', note: 'verb' },
  singst: { en: 'sing', note: 'singen · du' },
  schlafe: { en: 'sleep', note: 'schlafen · ich' },

  // ── plural forms shown in the lessons ──
  stunden: { en: 'hours', note: 'plural of die Stunde' },
  jahre: { en: 'years', note: 'plural of das Jahr' },
  buchstaben: { en: 'letters of the alphabet', note: 'plural of der Buchstabe' },
  personen: { en: 'people', note: 'plural of die Person' },
  wörter: { en: 'words', note: 'plural of das Wort' },
  kollegen: { en: 'colleagues', note: 'plural of der Kollege' },
  hobbys: { en: 'hobbies', note: 'plural of das Hobby' },
  namen: { en: 'names', note: 'plural of der Name' },
  zahlen: { en: 'numbers', note: 'plural of die Zahl' },
  minuten: { en: 'minutes', note: 'plural of die Minute' },
  seiten: { en: 'pages', note: 'plural of die Seite' },
  monate: { en: 'months', note: 'plural of der Monat' },

  // ── parts of fixed greetings ──
  abend: { en: 'evening', note: 'der · guten Abend' },
  nacht: { en: 'night', note: 'die · gute Nacht' },
  wasser: { en: 'water', note: 'das' },
  käse: { en: 'cheese', note: 'der' },
  müde: { en: 'tired', note: 'adjective' },
  ungarn: { en: 'Hungary', note: 'country' },
  ungarisch: { en: 'Hungarian', note: 'language' },
  bulgarien: { en: 'Bulgaria', note: 'country' },
  bulgarisch: { en: 'Bulgarian', note: 'language' },
  dänemark: { en: 'Denmark', note: 'country' },
  dänisch: { en: 'Danish', note: 'language' },
  chinesisch: { en: 'Chinese', note: 'language' },
  italienisch: { en: 'Italian', note: 'language' },
  polnisch: { en: 'Polish', note: 'language' },
  russisch: { en: 'Russian', note: 'language' },
  arabisch: { en: 'Arabic', note: 'language' },
  kleinkinder: { en: 'young children', note: 'plural · under six' },
  kinder: { en: 'children', note: 'plural of das Kind' },
  fremde: { en: 'strangers', note: 'der/die Fremde' },
  anrede: { en: 'form of address', note: 'die' },

  // ── prepositions & connectors ──
  aus: { en: 'from, out of', note: 'preposition' },
  in: { en: 'in', note: 'preposition' },
  an: { en: 'at, on', note: 'preposition' },
  auf: { en: 'on', note: 'preposition' },
  mit: { en: 'with', note: 'preposition' },
  für: { en: 'for', note: 'preposition' },
  ohne: { en: 'without', note: 'preposition' },
  bei: { en: 'at, with, near', note: 'preposition' },
  nach: { en: 'to, after', note: 'preposition' },
  von: { en: 'of, from', note: 'preposition' },
  zu: { en: 'to, too', note: 'preposition / adverb' },
  über: { en: 'over, about', note: 'preposition' },
  neben: { en: 'next to', note: 'preposition' },
  und: { en: 'and', note: 'conjunction' },
  aber: { en: 'but', note: 'conjunction' },
  oder: { en: 'or', note: 'conjunction' },
  also: { en: 'so, well then', note: 'discourse word' },
  dann: { en: 'then', note: 'adverb' },

  // ── common adverbs & particles ──
  nicht: { en: 'not', note: 'negation' },
  nein: { en: 'no', note: 'answer' },
  ja: { en: 'yes', note: 'answer' },
  auch: { en: 'also, too', note: 'adverb' },
  nur: { en: 'only', note: 'adverb' },
  sehr: { en: 'very', note: 'adverb' },
  immer: { en: 'always', note: 'adverb' },
  jetzt: { en: 'now', note: 'adverb' },
  heute: { en: 'today', note: 'adverb' },
  morgen: { en: 'tomorrow', note: 'adverb (der Morgen = morning)' },
  hier: { en: 'here', note: 'adverb' },
  da: { en: 'there', note: 'adverb' },
  dort: { en: 'there', note: 'adverb' },
  schon: { en: 'already', note: 'adverb' },
  wieder: { en: 'again', note: 'adverb' },
  gern: { en: 'gladly, like doing', note: 'adverb' },
  leider: { en: 'unfortunately', note: 'adverb' },
  natürlich: { en: 'of course, naturally', note: 'adverb' },
  vielleicht: { en: 'maybe', note: 'adverb' },
  zusammen: { en: 'together', note: 'adverb' },
  langsam: { en: 'slow, slowly', note: 'adjective/adverb' },
  langsamer: { en: 'slower', note: 'comparative of langsam' },
  schnell: { en: 'fast, quickly', note: 'adjective/adverb' },
  bitte: { en: 'please / you are welcome', note: 'politeness word' },
  danke: { en: 'thank you', note: 'politeness word' },
  einmal: { en: 'once', note: 'adverb · noch einmal = once more' },
  mal: { en: 'time(s), just', note: 'particle' },
  ganz: { en: 'quite, completely', note: 'adverb' },
  etwas: { en: 'something, a bit', note: 'pronoun' },
  alles: { en: 'everything', note: 'pronoun' },
  nichts: { en: 'nothing', note: 'pronoun' },
  viel: { en: 'much, a lot', note: 'quantifier' },
  mehr: { en: 'more', note: 'quantifier' },
  bisschen: { en: 'a bit', note: 'ein bisschen = a little' },
  spät: { en: 'late', note: 'adjective · zu spät = too late' },
  bis: { en: 'until, see you', note: 'preposition · bis bald = see you soon' },
  bald: { en: 'soon', note: 'adverb' },
  herein: { en: 'in, inside', note: 'adverb · kommen Sie herein = come in' },
  herzlich: { en: 'warmly, cordially', note: 'adjective' },
  willkommen: { en: 'welcome', note: 'greeting' },
  freut: { en: 'pleases', note: 'freut mich = nice to meet you' },
  stimmt: { en: 'is correct', note: 'stimmen · das stimmt = that is right' },

  // ── adjectives ──
  gut: { en: 'good, well', note: 'adjective' },
  schlecht: { en: 'bad', note: 'adjective' },
  groß: { en: 'big, tall', note: 'adjective' },
  große: { en: 'big', note: 'groß · inflected' },
  klein: { en: 'small', note: 'adjective' },
  neu: { en: 'new', note: 'adjective' },
  alt: { en: 'old', note: 'adjective · also "years old"' },
  jung: { en: 'young', note: 'adjective' },
  schön: { en: 'beautiful, nice', note: 'adjective' },
  schöne: { en: 'beautiful', note: 'schön · inflected' },
  nett: { en: 'nice, kind', note: 'adjective' },
  richtig: { en: 'correct, right', note: 'adjective' },
  falsch: { en: 'wrong', note: 'adjective' },
  wichtig: { en: 'important', note: 'adjective' },
  schwer: { en: 'difficult, heavy', note: 'adjective' },
  leicht: { en: 'easy, light', note: 'adjective' },
  interessant: { en: 'interesting', note: 'adjective' },
  bequem: { en: 'comfortable', note: 'adjective' },
  kaputt: { en: 'broken', note: 'adjective' },
  offen: { en: 'open', note: 'adjective' },
  rot: { en: 'red', note: 'colour' },
  verheiratet: { en: 'married', note: 'adjective' },
  ledig: { en: 'single, unmarried', note: 'adjective' },
  voll: { en: 'full', note: 'adjective' },

  // ── greetings ──
  hallo: { en: 'hello', note: 'greeting' },
  tschüss: { en: 'bye', note: 'informal farewell' },
  guten: { en: 'good', note: 'inflected form of gut in greetings' },
  gute: { en: 'good', note: 'inflected form of gut in greetings' },
  wiedersehen: { en: 'seeing again', note: 'auf Wiedersehen = goodbye' },
  ciao: { en: 'bye', note: 'informal farewell' },

  // ── numbers ──
  null: { en: 'zero', note: 'number' },
  eins: { en: 'one', note: 'number' },
  zwei: { en: 'two', note: 'number' },
  zwo: { en: 'two', note: 'spoken variant used on the phone' },
  drei: { en: 'three', note: 'number' },
  vier: { en: 'four', note: 'number' },
  fünf: { en: 'five', note: 'number' },
  sechs: { en: 'six', note: 'number' },
  sieben: { en: 'seven', note: 'number' },
  acht: { en: 'eight', note: 'number' },
  neun: { en: 'nine', note: 'number' },
  zehn: { en: 'ten', note: 'number' },
  elf: { en: 'eleven', note: 'number' },
  zwölf: { en: 'twelve', note: 'number' },
  dreizehn: { en: 'thirteen', note: 'number' },
  vierzehn: { en: 'fourteen', note: 'number' },
  fünfzehn: { en: 'fifteen', note: 'number' },
  sechzehn: { en: 'sixteen', note: 'number · sechs loses its s' },
  siebzehn: { en: 'seventeen', note: 'number · sieben loses -en' },
  achtzehn: { en: 'eighteen', note: 'number' },
  neunzehn: { en: 'nineteen', note: 'number' },
  zwanzig: { en: 'twenty', note: 'number' },
  einundzwanzig: { en: 'twenty-one', note: 'literally one-and-twenty' },
  zweiundzwanzig: { en: 'twenty-two', note: 'literally two-and-twenty' },
  dreißig: { en: 'thirty', note: 'number · spelled with ß' },
  vierzig: { en: 'forty', note: 'number' },
  fünfzig: { en: 'fifty', note: 'number' },
  sechzig: { en: 'sixty', note: 'number · sechs loses its s' },
  siebzig: { en: 'seventy', note: 'number · sieben loses -en' },
  achtzig: { en: 'eighty', note: 'number' },
  neunzig: { en: 'ninety', note: 'number' },
  hundert: { en: 'hundred', note: 'number' },

  // ── countries, languages, nationalities ──
  deutschland: { en: 'Germany', note: 'country' },
  indien: { en: 'India', note: 'country' },
  österreich: { en: 'Austria', note: 'country' },
  schweiz: { en: 'Switzerland', note: 'country · die Schweiz' },
  frankreich: { en: 'France', note: 'country' },
  spanien: { en: 'Spain', note: 'country' },
  türkei: { en: 'Turkey', note: 'country · die Türkei' },
  england: { en: 'England', note: 'country' },
  europa: { en: 'Europe', note: 'continent' },
  berlin: { en: 'Berlin', note: 'city' },
  münchen: { en: 'Munich', note: 'city' },
  hamburg: { en: 'Hamburg', note: 'city' },
  wien: { en: 'Vienna', note: 'city' },
  deutsch: { en: 'German (language)', note: 'language' },
  englisch: { en: 'English', note: 'language' },
  hindi: { en: 'Hindi', note: 'language' },
  spanisch: { en: 'Spanish', note: 'language' },
  französisch: { en: 'French', note: 'language' },
  türkisch: { en: 'Turkish', note: 'language' },
  inder: { en: 'Indian (man)', note: 'nationality' },
  inderin: { en: 'Indian (woman)', note: 'nationality' },
  deutscher: { en: 'German (man)', note: 'nationality' },
  deutsche: { en: 'German (woman)', note: 'nationality' },
  informatik: { en: 'computer science', note: 'subject' },

  // ── nouns that appear in notes but are not day vocabulary ──
  apfel: { en: 'apple', note: 'der · plural: die Äpfel' },
  haus: { en: 'house', note: 'das · plural: die Häuser' },
  häuser: { en: 'houses', note: 'plural of das Haus' },
  mann: { en: 'man, husband', note: 'der · plural: die Männer' },
  straße: { en: 'street', note: 'die · plural: die Straßen' },
  schule: { en: 'school', note: 'die · plural: die Schulen' },
  woche: { en: 'week', note: 'die · plural: die Wochen' },
  uhr: { en: "clock, o'clock", note: 'die · plural: die Uhren' },
  sonne: { en: 'sun', note: 'die' },
  wein: { en: 'wine', note: 'der' },
  dank: { en: 'thanks', note: 'der' },
  ende: { en: 'end', note: 'das' },
  person: { en: 'person', note: 'die · plural: die Personen' },
  quelle: { en: 'source, spring', note: 'die' },
  taxi: { en: 'taxi', note: 'das · plural: die Taxis' },
  onkel: { en: 'uncle', note: 'der' },
  tante: { en: 'aunt', note: 'die' },
  mädchen: { en: 'girl', note: 'das · -chen words are always neuter' },
  junge: { en: 'boy', note: 'der · plural: die Jungen' },
  brötchen: { en: 'bread roll', note: 'das' },
  fräulein: { en: 'young lady (dated)', note: 'das' },
  zentrum: { en: 'centre', note: 'das' },
  dokument: { en: 'document', note: 'das' },
  thema: { en: 'topic', note: 'das' },
  hotel: { en: 'hotel', note: 'das' },
  baby: { en: 'baby', note: 'das' },
  gold: { en: 'gold', note: 'das' },
  geschäft: { en: 'shop, business', note: 'das' },
  gemüse: { en: 'vegetables', note: 'das' },
  frühling: { en: 'spring (season)', note: 'der' },
  sommer: { en: 'summer', note: 'der' },
  winter: { en: 'winter', note: 'der' },
  montag: { en: 'Monday', note: 'der' },
  mai: { en: 'May', note: 'der' },
  norden: { en: 'north', note: 'der' },
  regen: { en: 'rain', note: 'der' },
  schnee: { en: 'snow', note: 'der' },
  wind: { en: 'wind', note: 'der' },
  fernseher: { en: 'television set', note: 'der' },
  gesundheit: { en: 'health', note: 'die · -heit is always feminine' },
  möglichkeit: { en: 'possibility', note: 'die · -keit is always feminine' },
  freiheit: { en: 'freedom', note: 'die' },
  freundschaft: { en: 'friendship', note: 'die · -schaft is always feminine' },
  nation: { en: 'nation', note: 'die · -ion is always feminine' },
  universität: { en: 'university', note: 'die · -tät is always feminine' },
  rechnung: { en: 'bill, invoice', note: 'die · -ung is always feminine' },
  million: { en: 'million', note: 'die' },
  tourismus: { en: 'tourism', note: 'der' },
  praktikant: { en: 'intern', note: 'der' },
  läden: { en: 'shops', note: 'plural of der Laden' },
  bahnhof: { en: 'train station', note: 'der' },
  platz: { en: 'space, square, seat', note: 'der' },
  euro: { en: 'euro', note: 'der' },
  bleistift: { en: 'pencil', note: 'der' },
  fußball: { en: 'football, soccer', note: 'der' },
  glück: { en: 'luck, happiness', note: 'das' },
  koch: { en: 'cook, chef', note: 'der · die Köchin' },
  köchin: { en: 'cook, chef (woman)', note: 'die' },
  kellner: { en: 'waiter', note: 'der · die Kellnerin' },
  verkäufer: { en: 'salesperson', note: 'der · die Verkäuferin' },
  verkäuferin: { en: 'salesperson (woman)', note: 'die' },
  programmierer: { en: 'programmer', note: 'der' },
  ärztin: { en: 'doctor (woman)', note: 'die · umlaut + -in' },
  lehrerin: { en: 'teacher (woman)', note: 'die' },
  studentin: { en: 'student (woman)', note: 'die' },
  ingenieurin: { en: 'engineer (woman)', note: 'die' },
  sekretärin: { en: 'secretary', note: 'die' },
  großeltern: { en: 'grandparents', note: 'plural only' },
  anmeldung: { en: 'registration', note: 'die' },
  sprachkurs: { en: 'language course', note: 'der' },
  klassenzimmer: { en: 'classroom', note: 'das' },
  möbelgeschäft: { en: 'furniture shop', note: 'das' },
  café: { en: 'café', note: 'das' },
  kurs: { en: 'course', note: 'der' },
  familienfotos: { en: 'family photos', note: 'plural' },
  buchstabe: { en: 'letter of the alphabet', note: 'der · plural: die Buchstaben' },
  alphabet: { en: 'alphabet', note: 'das' },
  beispiel: { en: 'example', note: 'das' },
  regel: { en: 'rule', note: 'die' },
  meister: { en: 'master', note: 'der' },
  eltern: { en: 'parents', note: 'plural only' },
  geschwister: { en: 'siblings', note: 'plural only' },
  freunde: { en: 'friends', note: 'plural of der Freund' },
  bücher: { en: 'books', note: 'plural of das Buch' },
  tische: { en: 'tables', note: 'plural of der Tisch' },
  lampen: { en: 'lamps', note: 'plural of die Lampe' },
  frauen: { en: 'women', note: 'plural of die Frau' },
  länder: { en: 'countries', note: 'plural of das Land' },
  städte: { en: 'cities', note: 'plural of die Stadt' },
  sprachen: { en: 'languages', note: 'plural of die Sprache' },
  hausaufgabe: { en: 'homework', note: 'die' },
  hausaufgaben: { en: 'homework', note: 'plural of die Hausaufgabe' },
  kugelschreiber: { en: 'ballpoint pen', note: 'der' },
}

/** Course vocabulary is authoritative; EXTRA fills the gaps around it. */
function buildIndex(): Map<string, Gloss> {
  const map = new Map<string, Gloss>()

  for (const [k, v] of Object.entries(EXTRA)) map.set(k, v)

  for (const v of ALL_VOCAB) {
    const article = v.de.match(/^(der|die|das)\s+/i)?.[1]
    const note = [article, v.pl ? `plural: ${v.pl}` : null].filter(Boolean).join(' · ') || undefined

    // full form ("der Tisch") and the bare noun ("Tisch")
    const forms = new Set([v.de, bareNoun(v.de)])
    for (const f of forms) {
      const key = f.toLowerCase()
      // never let a multi-word phrase overwrite a precise single-word entry
      if (map.has(key) && f.includes(' ')) continue
      map.set(key, { en: v.en, note })
    }
  }

  return map
}

let index: Map<string, Gloss> | null = null

/** Look up one surface form. Returns null when we are not sure — never a guess. */
export function lookup(raw: string): Gloss | null {
  if (!index) index = buildIndex()
  const word = raw.replace(/^[^\p{L}]+|[^\p{L}]+$/gu, '')
  if (word.length < 2) return null
  return index.get(word.toLowerCase()) ?? null
}

export function hasGloss(raw: string): boolean {
  return lookup(raw) !== null
}
